// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockCreditReport.Data;

#nullable disable

namespace MockCreditReport.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MockCreditReport.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreditReportId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreditReportId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MockCreditReport.Models.CollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClosedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreditReportId")
                        .HasColumnType("int");

                    b.Property<string>("OpenedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreditReportId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("MockCreditReport.Models.CreditReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PrimaryInsuredId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryInsuredId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryInsuredId");

                    b.HasIndex("SecondaryInsuredId");

                    b.ToTable("CreditReports");
                });

            modelBuilder.Entity("MockCreditReport.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreditReportId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inquirer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreditReportId");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("MockCreditReport.Models.Insured", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SsnLast4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Insureds");
                });

            modelBuilder.Entity("MockCreditReport.Models.PaymentHistorySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastLatePaymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LatePayments")
                        .HasColumnType("int");

                    b.Property<int>("OnTimePayments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentHistorySummaries");
                });

            modelBuilder.Entity("MockCreditReport.Models.PublicRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Court")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreditReportId")
                        .HasColumnType("int");

                    b.Property<string>("FileDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreditReportId");

                    b.ToTable("PublicRecords");
                });

            modelBuilder.Entity("MockCreditReport.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClosedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreditReportId")
                        .HasColumnType("int");

                    b.Property<string>("CreditorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PaymentHistorySummaryId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreditReportId");

                    b.HasIndex("PaymentHistorySummaryId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("MockCreditReport.Models.Address", b =>
                {
                    b.HasOne("MockCreditReport.Models.CreditReport", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CreditReportId");
                });

            modelBuilder.Entity("MockCreditReport.Models.CollectionItem", b =>
                {
                    b.HasOne("MockCreditReport.Models.CreditReport", null)
                        .WithMany("Collections")
                        .HasForeignKey("CreditReportId");
                });

            modelBuilder.Entity("MockCreditReport.Models.CreditReport", b =>
                {
                    b.HasOne("MockCreditReport.Models.Insured", "PrimaryInsured")
                        .WithMany()
                        .HasForeignKey("PrimaryInsuredId");

                    b.HasOne("MockCreditReport.Models.Insured", "SecondaryInsured")
                        .WithMany()
                        .HasForeignKey("SecondaryInsuredId");

                    b.Navigation("PrimaryInsured");

                    b.Navigation("SecondaryInsured");
                });

            modelBuilder.Entity("MockCreditReport.Models.Inquiry", b =>
                {
                    b.HasOne("MockCreditReport.Models.CreditReport", null)
                        .WithMany("Inquiries")
                        .HasForeignKey("CreditReportId");
                });

            modelBuilder.Entity("MockCreditReport.Models.Insured", b =>
                {
                    b.HasOne("MockCreditReport.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MockCreditReport.Models.PublicRecord", b =>
                {
                    b.HasOne("MockCreditReport.Models.CreditReport", null)
                        .WithMany("PublicRecords")
                        .HasForeignKey("CreditReportId");
                });

            modelBuilder.Entity("MockCreditReport.Models.Trade", b =>
                {
                    b.HasOne("MockCreditReport.Models.CreditReport", null)
                        .WithMany("Trades")
                        .HasForeignKey("CreditReportId");

                    b.HasOne("MockCreditReport.Models.PaymentHistorySummary", "PaymentHistorySummary")
                        .WithMany()
                        .HasForeignKey("PaymentHistorySummaryId");

                    b.Navigation("PaymentHistorySummary");
                });

            modelBuilder.Entity("MockCreditReport.Models.CreditReport", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Collections");

                    b.Navigation("Inquiries");

                    b.Navigation("PublicRecords");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
